#!/bin/sh

# Script for installation of PRISM-games on a clean install of Ubuntu

set -e # Abort if one of the commands fails
set -x # Print commands as they are executed

# Install dependencies: make/gcc/Java/git
sudo apt-get -y update
sudo apt -y install make gcc g++ default-jdk git

# Install Python (only needed for testing (prism-auto) currently)
sudo apt -y install python3

# Download the latest development version from GitHub
git clone https://github.com/prismmodelchecker/prism-games.git

# Compile PRISM-games and run a few tests
# (each should display: "Testing result: PASS")
(cd prism-games/prism && make && make test testyices testz3 testppl)
